"""Write llms.txt and llms-full.txt for the documentation site.

``llms.txt`` (see https://llmstxt.org) is a short Markdown index that tells AI assistants
what the package is and where its documentation lives. ``llms-full.txt`` is the whole
documentation as plain text, including the API reference generated by autodoc, so an
assistant can read it in a single fetch.

The text comes from Sphinx's ``text`` builder, which renders the finished pages
(autodoc output included) rather than the ``.rst`` sources. Pages are taken in the order
of the toctree in ``index.rst``. Run after the HTML build::

    make html llms          # from docs/

The files are written into ``build/html`` so they are published with the site.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from importlib.metadata import metadata
from pathlib import Path

DOCS = Path(__file__).resolve().parent
SOURCE = DOCS / "source"
TEXT = DOCS / "build" / "text"
HTML = DOCS / "build" / "html"

# Links that belong in llms.txt but aren't pages of this site
EXTRA_LINKS = [
    ("bdsim wiki", "https://github.com/petercorke/bdsim/wiki", "tutorials, worked examples and design notes"),
    ("Example notebooks", "https://github.com/petercorke/bdsim/tree/main/docs/notebooks", "Jupyter notebooks, also runnable in the browser from the documentation site"),
    ("Source code", "https://github.com/petercorke/bdsim", "GitHub repository; examples are in examples/"),
    ("PyPI", "https://pypi.org/project/bdsim/", "install with pip install bdsim"),
    ("RVC ecosystem", "https://github.com/petercorke/rvc-ecosystem", "how bdsim relates to the Robotics and Machine Vision Toolboxes"),
]


def toctree_pages(index: Path) -> list[str]:
    """Document names listed in the toctrees of the master document, in order.

    :param index: the master document, ``index.rst``
    :return: document names such as ``"bdsim.blocks"``
    """
    pages, in_toctree = [], False
    for line in index.read_text().splitlines():
        if line.startswith(".. toctree::"):
            in_toctree = True
        elif in_toctree and line.strip() and not line.startswith((" ", "\t")):
            in_toctree = False  # the directive's indented body has ended
        elif in_toctree and line.strip() and not line.strip().startswith(":"):
            pages.append(line.strip())
    return pages


def title(text: str) -> str:
    """The page title: the first line, which the text builder underlines."""
    return text.splitlines()[0].strip()


def main() -> None:
    meta = metadata("bdsim")  # the installed package, as built from pyproject.toml
    urls = dict(u.split(", ", 1) for u in meta.get_all("Project-URL"))
    base = urls["documentation"].rstrip("/") + "/"

    subprocess.run(
        [os.environ.get("SPHINXBUILD", "sphinx-build"), "-q", "-b", "text", str(SOURCE), str(TEXT)],
        check=True,
    )
    pages = ["index"] + toctree_pages(SOURCE / "index.rst")
    texts = {p: (TEXT / f"{p}.txt").read_text() for p in pages}

    name = meta["Name"]
    summary = meta["Summary"]
    index = [
        f"# {name}",
        "",
        f"> {summary}. This is the documentation site for the `{name}` Python package.",
        "",
        f"The complete documentation, including the API reference for every class and block, "
        f"is available as a single text file: [llms-full.txt]({base}llms-full.txt).",
        "",
        "## Documentation",
        "",
        *(f"- [{title(texts[p])}]({base}{p}.html)" for p in pages),
        "",
        "## Optional",
        "",
        *(f"- [{label}]({url}): {note}" for label, url, note in EXTRA_LINKS),
        "",
    ]
    HTML.mkdir(parents=True, exist_ok=True)
    (HTML / "llms.txt").write_text("\n".join(index))

    sections = [f"# {name}: {summary}\n\nDocumentation: {base}\n"]
    for p in pages:
        sections.append(f"\n{'=' * 72}\nPage: {base}{p}.html\n{'=' * 72}\n\n{texts[p].strip()}\n")
    full = "".join(sections)
    full = re.sub(r"\n{3,}", "\n\n", full)  # the text builder leaves runs of blank lines
    (HTML / "llms-full.txt").write_text(full)
    print(f"llms.txt: {len(pages)} pages; llms-full.txt: {len(full) // 1000} kB", file=sys.stderr)


if __name__ == "__main__":
    main()
