"""
Continuous-time blocks:

- have inputs and outputs
- have state variables
- are a subclass of ``ContinuousBlock`` |rarr| ``Block``
"""

from __future__ import annotations
from typing import Any, Callable


import numpy as np
import scipy.signal
import math
from math import sin, cos, atan2, sqrt, pi
import spatialmath.base as smb  # type: ignore[import-not-found]
from spatialmath import SE3, Twist3  # type: ignore[import-not-found]

from bdsim.blockdiagram import BlockDiagram
from bdsim.components import ContinuousBlock, SubsystemBlock

Vector1D = int | float | tuple[float, ...] | list[float] | np.ndarray


class Integrator(ContinuousBlock):
    r"""
    :blockname:`INTEGRATOR`

    Continuous-time integrator.

    :inputs: 1
    :outputs: 1
    :states: N

    .. list-table::
        :header-rows: 1

        *   - Port type
            - Port number
            - Types
            - Description
        *   - Input
            - 0
            - float, ndarray
            - :math:`x`
        *   - Output
            - 0
            - any
            - :math:`y`

    This block implements the dynamics of a continuous-time integrator with gain :math:`k`, which is given by

    .. math::

        \begin{aligned}
        x(t) &= k \int_0^T u(t) \, dt \\
        y(t) &= x(t)
        \end{aligned}

    The state can be a scalar or a vector. The initial state, and type, is given by
    ``x0``.  The shape of the input signal must match ``x0``.

    The minimum and maximum output values can be:

        - a scalar, in which case the same value applies to every element of
          the state vector, or
        - a vector, of the same shape as ``x0`` that applies elementwise to
          the state.

    .. note:: The minimum and maximum prevent integration outside the limits,
        but assume that the initial state is within the limits.

    Integration can be controlled by an ``enable`` function::

        enable(t, u, x): bool

    where the arguments are current time, a list of inputs to the integrator block and the state
    as an ndarray.  If the function returns False then the integrator's state is set
    to zero.

    .. todo:: Make enable an optional input to the block, or the input for a subclassed
        variant of the block.

    :seealso: :class:`Deriv`
    """

    nin = 1
    nout = 1

    def __init__(
        self,
        x0: Vector1D = 0,
        gain: float = 1.0,
        min: Vector1D | None = None,
        max: Vector1D | None = None,
        **blockargs: Any,
    ) -> None:
        """
        :param x0: Initial state, defaults to 0
        :type x0: array_like, optional
        :param gain: gain or scaling factor, defaults to 1
        :type gain: float
        :param min: Minimum value of state, defaults to None
        :type min: float or array_like, optional
        :param max: Maximum value of state, defaults to None
        :type max: float or array_like, optional
        :param blockargs: |BlockOptions|
        :type blockargs: dict
        """

        # TODO: event handling to properly deal with state hitting limits, rather than just clipping the state and setting the derivative to zero.
        # TODO: reinstate enable, using event handling, but also as an optional input to the block, rather than a function argument.  This would allow the enable signal to be generated by another block, and would allow the integrator to be enabled and disabled multiple times during a simulation.

        if isinstance(x0, np.ndarray):
            if x0.ndim > 1:
                raise ValueError("state must be a 1D vector")
        else:
            x0 = smb.getvector(x0)

        x0 = np.array(x0, dtype=float).reshape(-1)

        nstates = x0.shape[0]

        super().__init__(nstates=nstates, **blockargs)

        if min is not None:
            min = smb.getvector(min, nstates)
        if max is not None:
            max = smb.getvector(max, nstates)

        self._x0 = x0
        self.min = min
        self.max = max
        self.gain: float = gain

        # TODO: event
        # self.enable = enable
        # if enable is not None and not callable(enable):
        #     raise ValueError("enable must be callable")
        # # print("nstates", self.nstates)

    def output(self, t: float, u: list[Any], x: np.ndarray) -> list[Any]:
        return [x]

    def deriv(self, t: float, u: list[Any], x: np.ndarray) -> np.ndarray:
        xd = smb.getvector(u[0])
        # TODO: event
        # if self.enable is not None and not self.enable(t, u, x):
        #     # if enable function returns False then integrator output is jammed at zero
        #     x[:] = 0.0
        #     return np.zeros(x.shape)

        # stop integration if state is outside limits
        if self.min is not None:
            xd[x < self.min] = 0
        if self.max is not None:
            xd[x > self.max] = 0

        return self.gain * xd


class PoseIntegrator(ContinuousBlock):
    r"""
    :blockname:`POSEINTEGRATOR`

    Continuous-time pose integrator

    :inputs: 1
    :outputs: 1
    :states: 6

    .. list-table::
        :header-rows: 1

        *   - Port type
            - Port number
            - Types
            - Description
        *   - Input
            - 0
            - ndarray(6,)
            - :math:`x`
        *   - Output
            - 0
            - SE3
            - :math:`y`

    This block integrates spatial velocity over time. The block input is a spatial
    velocity as a 6-vector :math:`(v_x, v_y, v_z, \omega_x, \omega_y, \omega_z)` and the
    output is pose as an ``SE3`` instance.

    .. note:: The state vector is a velocity twist.
    """

    nin = 1
    nout = 1

    def __init__(self, x0: SE3 | Twist3 | None = None, **blockargs: Any) -> None:
        r"""
        :param x0: Initial pose, defaults to null
        :type x0: SE3, Twist3, optional
        :param blockargs: |BlockOptions|
        :type blockargs: dict
        """

        if x0 is None:
            _x0 = np.zeros((6,))
        elif isinstance(x0, SE3):
            _x0 = Twist3(x0).A
        elif isinstance(x0, Twist3):
            _x0 = x0.A

        nstates = len(_x0)

        super().__init__(nstates=nstates, **blockargs)

        self._x0 = _x0

    def output(self, t: float, u: list[Any], x: np.ndarray) -> list[SE3]:
        return [Twist3(x).SE3(1)]

    def deriv(self, t: float, u: list[Any], x: np.ndarray) -> Any:
        return u[0]


# ------------------------------------------------------------------------ #


class LTI_SS(ContinuousBlock):
    r"""
    :blockname:`LTI_SS`

    Continuous-time state-space LTI dynamics

    :inputs: 1
    :outputs: 1
    :states: N

    .. list-table::
        :header-rows: 1

        *   - Port type
            - Port number
            - Types
            - Description
        *   - Input
            - 0
            - float, ndarray
            - :math:`u`
        *   - Output
            - 0
            - float, ndarray
            - :math:`y`

    Implements the dynamics of a continuous-time multi-input multi-output (MIMO) linear
    time invariant (LTI) system described in statespace form.  The dynamics are given by

    .. math::

        \begin{aligned}
        \dot{x} &= A x + B u \\
        y &= C x
        \end{aligned}

    A direct passthrough component, typically :math:`D`, is not allowed in order
    to avoid algebraic loops.

    Examples::

        lti = bd.LTI_SS(A=-2, B=1, C=-1)

    is the system :math:`\dot{x}=-2x+u, y=-x`.
    """

    nin = 1
    nout = 1

    def __init__(
        self,
        A: np.ndarray,
        B: np.ndarray,
        C: np.ndarray,
        D: np.ndarray | None = None,
        x0: np.ndarray | None = None,
        **blockargs: Any,
    ) -> None:
        r"""
        :param N: numerator coefficients, defaults to 1
        :type N: array_like, optional
        :param A: system matrix, defaults to [1,1]
        :type A: array_like, optional
        :param B: input matrix, defaults to [1]
        :type B: array_like, optional
        :param C: output matrix, defaults to [1]
        :type C: array_like, optional
        :param D: feedthrough matrix, defaults to None
        :type D: array_like, optional
        :param x0: initial states, defaults to None
        :type x0: array_like, optional
        :param blockargs: |BlockOptions|
        :type blockargs: dict
        """
        # print('in SS constructor')
        assert A.shape[0] == A.shape[1], "A must be square"
        n = A.shape[0]
        if len(B.shape) == 1:
            # 1D array, assume it's a column vector and reshape to (n,1)
            nin = 1
            B = B.reshape((n, 1))
        else:
            nin = B.shape[1]
        assert B.shape[0] == n, "B must have same number of rows as A"

        if len(C.shape) == 1:
            # 1D array, assume it's a row vector and reshape to (1,n)
            nout = 1
            assert C.shape[0] == n, "C must have same number of columns as A"
            C = C.reshape((1, n))
        else:
            nout = C.shape[0]
            assert C.shape[1] == n, "C must have same number of columns as A"

        if D is None:
            D = np.zeros((nout, n))
        elif len(D.shape) == 1:
            assert len(D) == nin * nout, "D must conform to B and C dimensions"
            D = D.reshape((nout, nin))
        else:
            assert D.shape == (nout, nin), "D must conform to B and C dimensions"

        self.A = A
        self.B = B
        self.C = C

        if np.any(D != 0):
            # flag we have feedthrough, which may create an algebraic loop
            self.D = D
            feedthrough = True
        else:
            self.D = None
            feedthrough = False

        super().__init__(nstates=n, x0=x0, feedthrough=feedthrough, **blockargs)

    def output(self, t: float, u: list[Any], x: np.ndarray) -> list[Any]:
        if self.D is not None:
            return list(self.C @ x + self.D @ u)
        else:
            return list(self.C @ x)

    def deriv(self, t: float, u: list[Any], x: np.ndarray) -> np.ndarray:
        # Reshape u and x to (N,1), i.e. column vectors, so
        # no problems with broadcasting between A@x and B@u
        x = x.reshape(-1, 1)
        u_arr = np.array(u).reshape(-1, 1)
        xd = self.A @ x + self.B @ u_arr
        return xd.flatten()


# ------------------------------------------------------------------------ #


def _tf2ss(
    num: Vector1d, den: Vector1d, form="ccf", order="backward", verbose=False
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    r"""
    :param N: Numerator coefficients in descending powers of :math:`s`.
    :type N: array_like
    :param D: Denominator coefficients in descending powers of :math:`s`.
        Does not have to be normalized.
    :type D: array_like
    :param form: The canonical form of the realization, defaults to 'ccf'.
    :type form: str, optional
    :param order: The state ordering convention
    :type order: str, optional
    :param verbose: _description_, defaults to False
    :type verbose: bool, optional
    :return: _description_
    :rtype: tuple[np.ndarray, np.ndarray, np.ndarray]

    Coefficients can be specified in the form of an array of coefficients, or an array of factors.
    For example:

        * ``[1, 2]`` is the polynomial :math:`s+2`,
        * ``[[1, 1], [1, 2]]`` is the factors :math:`(s+1)(s+2)` which are convolved to obtain the coefficients of :math:`s^2 + 3s + 2`.
        * ``[2,[1,1], [1,2]]`` is the factors :math:`2(s+1)(s+2)` which are convolved to obtain the coefficients of :math:`2s^2 + 6s + 4`

    The ``form`` of the realization can be one of:

        * ``'ccf'`` : Controller Canonical Form. The characteristic equation
          coefficients appear in a row of **A**. Useful for control design.
        * ``'ocf'`` : Observer Canonical Form. The characteristic equation
          coefficients appear in a column of **A**. Useful for estimation.

    The ``order`` of the integrator chain can be one of:

        * ``'forward'`` : :math:`x_0` is the output of the first integrator,
          :math:`x_n-1` is the last. Results in 1s on the super-diagonal for 'ccf'.
        * ``'backward'``: :math:`x_n-1` is the output of the first integrator,
          :math:`x_0` is the last. Results in 1s on the sub-diagonal for 'ccf'.

    .. note::
        - The transfer function must be *proper* (:math:`deg(N) <= deg(D)`).
        - If the transfer function is *strictly proper* (:math:`deg(N) < deg(D)`) then the D matrix is zero.
        - The default ``form='ccf', order='backward'`` corresponds to the state-space realization returned by ``scipy.signal.tf2ss`` and MATLAB's ``tf2ss``.
        - The state-space matrices are available in the ``A``, ``B``, ``C`` and ``D`` attributes of the block.
    """
    # normalize polynomials so leading coefficient of denominator is one

    def expand_poly(x) -> np.ndarray:
        # if x is an array of scalars, assume it's already in the correct form
        # otherwise assume it's an array of factors and convolve them together to get the coefficients
        #
        # eg. [1, 2] is already the coefficients of s+2,
        # eg. [[1, 1], [1, 2]] is the factors (s+1)(s+2) which are convolved to get the coefficients of s^2 + 3s + 2
        # eg. [2,[1,1], [1,2]] is the factors 2(s+1)(s+2) which are convolved to get the coefficients of 2s^2 + 6s + 4
        if isinstance(x, (int, float)):
            return np.array([x], dtype=float)
        if all(isinstance(c, (int, float)) for c in x):
            # array of scalars, assume it's already in the correct form
            return smb.getvector(x, dtype="float")

        coeffs = [1]
        for t in x:
            print(coeffs, t)
            coeffs = np.convolve(coeffs, t)
        return coeffs

    num = expand_poly(num)
    den = expand_poly(den)

    D0 = den[0]
    den = den / D0
    num = num / D0

    n = len(den) - 1
    m = len(num) - 1

    if m > n:
        raise ValueError(
            "System is non-causal (numerator degree > denominator degree)."
        )

    # Handle the D matrix (direct feedthrough)
    if m == n:
        D = np.array([[num[0]]])
        # Update numerator: num_new = num - D * den
        # This effectively performs the division to get the strictly proper part
        b_coeffs_full = num - D[0, 0] * den
    else:
        D = np.array([[0.0]])
        b_coeffs_full = num

    # Pad the updated numerator to length n (the strictly proper part)
    # b_coeffs will be [b1, b2, ... bn] for the strictly proper part
    b_coeffs = np.zeros(n)
    if n > 0:
        # Use the last n terms of the modified numerator
        b_coeffs[-len(b_coeffs_full[1:] if m == n else b_coeffs_full) :] = (
            b_coeffs_full[1:] if m == n else b_coeffs_full
        )

    # Denominator coefficients (ignoring leading 1)
    a_coeffs = den[1:]

    # Initialize matrices
    A = np.zeros((n, n))
    B = np.zeros((n, 1))
    C = np.zeros((1, n))

    if form == "ccf":
        # --- Controller Canonical Form ---
        if order == "forward":
            # Bottom row coeffs, super-diagonal 1s
            A[:-1, 1:] = np.eye(n - 1)
            A[-1, :] = -a_coeffs[::-1]
            B[-1, 0] = 1
            C[0, :] = b_coeffs[::-1]
        else:  # backward
            # Top row coeffs, sub-diagonal 1s (Matlab/Scipy style)
            A[1:, :-1] = np.eye(n - 1)
            A[0, :] = -a_coeffs
            B[0, 0] = 1
            C[0, :] = b_coeffs

    elif form == "ocf":
        # --- Observer Canonical Form ---
        if order == "forward":
            # Right column coeffs, sub-diagonal 1s
            A[1:, :-1] = np.eye(n - 1)
            A[:, -1] = -a_coeffs[::-1]
            B[:, 0] = b_coeffs[::-1]
            C[0, -1] = 1
        else:  # backward
            # Left column coeffs, super-diagonal 1s
            A[:-1, 1:] = np.eye(n - 1)
            A[:, 0] = -a_coeffs
            B[:, 0] = b_coeffs
            C[0, 0] = 1

    if verbose:
        print("A=", np.array2string(A, prefix="A="))
        print("B=", np.array2string(B, prefix="B="))
        print("C=", np.array2string(C, prefix="C="))
        print("D=", np.array2string(D, prefix="D="))

    return A, B, C, D


class LTI_SISO(LTI_SS):
    r"""
    :blockname:`LTI_SISO`

    Continuous-time SISO LTI dynamics.

    :inputs: 1
    :outputs: 1
    :states: N

    .. list-table::
        :header-rows: 1

        *   - Port type
            - Port number
            - Types
            - Description
        *   - Input
            - 0
            - float
            - :math:`u`
        *   - Output
            - 0
            - float
            - :math:`y`

    Implements the dynamics of a continuous-time single-input single-output (SISO) linear
    time invariant (LTI) system described by numerator and denominator
    polynomial coefficients.  The dynamics are given by

    .. math::

        \frac{Y(s)}{U(s)} = \frac{N(s)}{D(s)}

    Coefficients are given in the order from highest order to zeroth
    order, ie. :math:`2s^2 - 4s +3` is ``[2, -4, 3]``, :math:`s^3` is ``[1, 0, 0, 0]``.

    The state-space form can be either controller canonical form or observer canonical
    form, as specified by the ``form`` argument.

    Examples::

        lti = bd.LTI_SISO(N=[1, 2], D=[2, 3, -4])

    is the transfer function :math:`\frac{s+2}{2s^2+3s-4}`.

    .. note::
      * The state-space realization is not unique. The controller canonical form is more common
        in control design, while the observer canonical form is more common in estimation.
      * The state ordering convention (the direction of the integrator chain) can be
        specified by the ``order`` argument, and results in either 1s on the super-diagonal
        or sub-diagonal of the A matrix for the controller canonical form.
    """

    nin = 1
    nout = 1

    def __init__(
        self,
        N: Vector1D = 1,
        D: Vector1D = [1, 1],
        x0: np.ndarray | None = None,
        form="ccf",
        order="backward",
        verbose=False,
        **blockargs: Any,
    ) -> None:
        r"""
        :param N: Numerator coefficients in descending powers of :math:`s`.
        :type N: array_like
        :param D: Denominator coefficients in descending powers of :math:`s`.
            Does not have to be normalized.
        :type D: array_like
        :param form: The canonical form of the realization, defaults to 'ccf'.
        :type form: str, optional
        :param order: The state ordering convention
        :type order: str, optional
        :param verbose: If True, print the state-space matrices, defaults to False
        :type verbose: bool, optional
        :return: LTI_SISO block
        :rtype: ``LTI_SISO`` instance

        Coefficients ``N`` and ``D``can be specified in the form of an array of coefficients, or an array of factors.
        The coefficients and factors are arrays of coefficients in decreasing powers of :math:`s`.
        For example:

            * ``[1, 2]`` is the polynomial :math:`s+2`,
            * ``[[1, 1], [1, 2]]`` is the factors :math:`(s+1)(s+2)` which are convolved to obtain the coefficients of :math:`s^2 + 3s + 2`.
            * ``[2,[1,1], [1,2]]`` is the factors :math:`2(s+1)(s+2)` which are convolved to obtain the coefficients of :math:`2s^2 + 6s + 4`

        The ``form`` of the realization can be one of:

            * ``'ccf'`` : Controller Canonical Form. The characteristic equation
            coefficients appear in a row of **A**. Useful for control design.
            * ``'ocf'`` : Observer Canonical Form. The characteristic equation
            coefficients appear in a column of **A**. Useful for estimation.

        The ``order`` of the integrator chain can be one of:

            * ``'forward'`` : :math:`x_0` is the output of the first integrator,
            :math:`x_n-1` is the last. Results in 1s on the super-diagonal for 'ccf'.
            * ``'backward'``: :math:`x_n-1` is the output of the first integrator,
            :math:`x_0` is the last. Results in 1s on the sub-diagonal for 'ccf'.

        .. note::
            - The transfer function is assumed to be strictly proper (:math:`deg(N) < deg(D)`).
            - The default ``form='ccf', order='backward'`` corresponds to the state-space realization returned by ``scipy.signal.tf2ss`` and MATLAB's ``tf2ss``.
            - The state-space matrices are available in the ``A``, ``B``, ``C``, and ``D`` attributes of the block.
            - If D is zero, then the block has no feedthrough and the D matrix is set to None. If D is nonzero, then the block has feedthrough and the D matrix is stored in the D attribute.
            - The ``_feedthrough`` attribute of the block is set to True if D is nonzero. This can be used to check for feedthrough without having to check the D matrix directly, and is used
              by the scheduler to ensure correct block evaluation order.

        """

        A, B, C, D = _tf2ss(N, D, form=form, order=order, verbose=verbose)

        n = A.shape[0]
        if x0 is None:
            x0 = np.zeros((n,))

        super().__init__(A=A, B=B, C=C, D=D, x0=x0, **blockargs)

        # TODO: param
        #  def change_param(self, param: str, newvalue: np.ndarray) -> None:
        #     if param == "num":
        #         self.num = newvalue
        #     elif param == "den":
        #         self.den = newvalue
        #     self.A, self.B, self.C, self.D = scipy.signal.tf2ss(self.num, self.den)

        # self.add_param("num", change_param)
        # self.add_param("den", change_param)


# ------------------------------------------------------------------------ #


class Deriv2(LTI_SS):
    r"""
    :blockname:`DERIV2`

    Continuous-time derivative with second-order filter.

    :inputs: 1
    :outputs: 1
    :states: N

    .. list-table::
        :header-rows: 1

        *   - Port type
            - Port number
            - Types
            - Description
        *   - Input
            - 0
            - float
            - :math:`x`
        *   - Output
            - 0
            - float
            - :math:`y`

    Implements the dynamics of a derivative filter, but to be causal it includes a
    second-order low-pass filter.  The dynamics are

    .. math:: \frac{Y(s)}{U(s)} = \frac{s}{s^2 + 2\omega_n \zeta s + \omega_n^2}

    It is implemented in state-space form using an ``LTI_SS`` block. The state-space model is in observer canonical form, with the state
    vector being the output of the first and second integrators in the chain.  The
    initial state of the integrators is given by ``x0``.  The initial output of the
    derivative block is given by ``x0[0]``.


    :seealso: :class:`Integrator`
    """

    nin = 1
    nout = 1

    def __init__(
        self,
        wn: float,
        unit: str = "rad/s",
        zeta: float = 1,
        x0: Vector1D = (0, 0),
        gain: float = 1.0,
        **blockargs: Any,
    ) -> None:
        r"""
        :param wn: natural frequency in units of rad/s
        :type wn: float
        :param unit: units of wn, defaults to "rad/s"
        :type unit: str, optional
        :param zeta: damping ratio, defaults to 1
        :type zeta: float, optional
        :param x0: initial states, defaults to (0, 0)
        :type x0: array_like, optional
        :param gain: gain or scaling factor, defaults to 1
        :type gain: float, optional
        :param blockargs: |BlockOptions|
        :type blockargs: dict

        Damping factor defaults to critical damping, which results in the fastest response without overshoot.
        A smaller value of ``zeta`` results in a faster response but with overshoot, while a larger value results in a slower response with no overshoot.
        Choose ``zeta=0.707`` (:math:`1/\sqrt{2}`) for optimal rise time and overshoot (4.3%).
        """

        if unit == "Hz":
            wn = 2 * pi * wn
        N = [gain * wn**2, 0]  # wn^2 s
        D = [1, 2 * zeta * wn, wn**2]  # s^2 + 2 zeta wn s + wn^2

        A, B, C = _tf2ss(N, D, form="ocf")
        # form="ccf", order="backward"

        super().__init__(A=A, B=B, C=C, x0=x0, **blockargs)


# ------------------------------------------------------------------------ #

from bdsim.blocks.connections import SubSystem


class Deriv(SubsystemBlock):
    r"""
    :blockname:`DERIV`

    Continuous-time derivative.

    :inputs: 1
    :outputs: 1
    :states: N

    .. list-table::
        :header-rows: 1

        *   - Port type
            - Port number
            - Types
            - Description
        *   - Input
            - 0
            - float
            - :math:`x`
        *   - Output
            - 0
            - float
            - :math:`y`

    Implements the dynamics of a derivative filter, but to be causal (proper) it
    includes a first-order low-pass filter.  The dynamics is

    .. math:: \frac{s}{\frac{s}{\alpha} + 1}

    The pole is at :math:`s=-\alpha`. A small value of ``alpha`` corresponds to a
    long-time constant in the step reponse.   The parameter ``alpha`` can be used to
    achieve the desired tradeoff between noise reduction and phase lag.

    The derivative calculation is performed using a complementary filter,
    implemented as a subsystem with an integrator and a feedback loop.  The initial
    state of the integrator is given by ``x0``::


            +
        u ───> SUM ───────> GAIN(alpha) ──┬───>  GAIN(k) ───> y
                ▲ ─                       │
                │                         │
                └───  INTEGRATOR(x0) <────┘



    If the initial output of the derivative block is known it can be provided as
    ``y0`` from which ``x0`` is calculated by :math:`x_0 = - \alpha y_0`.

    The final GAIN block is only included if ``gain`` is not 1.0, and can be used to
    scale the output of the derivative block.

    .. warning::
        This derivative block has a direct feedthrough term, and depending on how it is used
        in a system it may introduce an an algebraic loop which will be flagged at
        ``compile`` time. The ``Deriv2`` blockis an alternative implementation without direct
        feedthrough and includes a second-order filter which may be more suitable for some applications.

    .. versionchanged:: 1.2.0
        The pole is now at :math:`s=-\alpha` instead of :math:`s=-1/\alpha`.

    :seealso: :class:`Integrator`
    """

    nin = 1
    nout = 1

    def __init__(
        self,
        alpha: float,
        x0: Vector1D = 0,
        y0: Vector1D | None = None,
        gain: float = 1.0,
        **blockargs: Any,
    ) -> None:
        r"""
        :param alpha: filter pole in units of rad/s
        :type alpha: float
        :param x0: initial states, defaults to 0
        :type x0: array_like, optional
        :param y0: inital outputs
        :type y0: array_like
        :param gain: gain or scaling factor, defaults to 1
        :type gain: float, optional
        :param blockargs: |BlockOptions|
        :type blockargs: dict
        """

        bd = blockargs["bd"]
        subsystem = bd.runtime.blockdiagram(name="PID")

        if y0 is not None:
            y0 = np.array(smb.getvector(y0), dtype=float).reshape(-1)
            x0 = -y0 * alpha

        integrator = subsystem.INTEGRATOR(x0=x0)
        inp = subsystem.INPORT(1, name="IN")
        outp = subsystem.OUTPORT(1, name="OUT")
        sum = subsystem.SUM("+-", name="SUM")
        alpha = subsystem.GAIN(alpha, name="alpha")

        subsystem.connect(inp, sum[0])
        subsystem.connect(sum[0], alpha)
        subsystem.connect(alpha, integrator)
        subsystem.connect(integrator, sum[1])
        if gain != 1.0:
            gain = subsystem.GAIN(gain, name="K")
            subsystem.connect(alpha, gain)
            subsystem.connect(gain, outp)
        else:
            subsystem.connect(alpha, outp)

        super().__init__(subsystem=subsystem, **blockargs)


# ------------------------------------------------------------------------ #


class PID(SubsystemBlock):
    r"""
    :blockname:`PID`

    Continuous-time PID control.

    :inputs: 2
    :outputs: 1
    :states: 2

    .. list-table::
        :header-rows: 1

        *   - Port type
            - Port number
            - Types
            - Description
        *   - Input
            - 0
            - float
            - :math:`x`, plant output
        *   - Input
            - 1
            - float
            - :math:`x^*`, demanded output
        *   - Output
            - 0
            - any
            - :math:`u`, control to plant

    Implements the dynamics of a continuous-timePID controller as a ``bdsim`` subsystem.
    There are three possible structures:

    * Parallel structure::

              ┌───> P ──────┐
              │             │
              │             ▼
        e ────┼───> Ds ──> SUM ───> y
              │             ▲
              │             │
              └───> I/s ────┘

    .. math::

            \begin{aligned}
            e &= x^* - x \\
            \frac{Y(s)}{E(s)} &= P + \frac{I}{s} + D s
            \end{aligned}


    * Ideal or standard structure. Described by ANSI/ISA-S75::

                    ┌─────────────┐
                    │             │
                    │             ▼
        e ────> P ──┼───> Ds ──> SUM ───> y
                    │             ▲
                    │             │
                    └───> I/s ────┘

    .. math::

        \begin{aligned}
        e &= x^* - x \\
        \frac{Y(s)}{E(s)} &= P \left(1 + \frac{I}{s} + D s\right)
        \end{aligned}


    * Series structure. Archaic form, essentially a PI controller followed by a PD controller::

                    ┌──────────────┐    ┌─────────────┐
                    │              │    │             │
                    │              ▼    │             ▼
        e ────> P ──┴──> I/s ───> SUM ──┴──>  Ds ──> SUM ───> y


    .. math::

        \begin{aligned}
        e &= x^* - x \\
        \frac{Y(s)}{E(s)} &= P \left(1 + \frac{I}{s}\right)\left(1 + D s\right)
        \end{aligned}

    Sometimes the gains are written in terms of time constants :math:`T_i = 1/I` and :math:`Td = D`.

    The PID controller is a subsytem comprising a number of blocks. If the I or D gains are
    zero then a PD or PI controller will be created with fewer blocks.

    The gain equivalence between the three structures is given by

    .. list-table::
        :header-rows: 1
        :align: center

        *   - structure
            - :math:`P`
            - :math:`I`
            - :math:`D`
        *   - parallel
            - :math:`P_p`
            - :math:`I_p`
            - :math:`D_p`
        *   - ideal
            - :math:`P_i`
            - :math:`P_i I_i`
            - :math:`P_i D_i`
        *   - series
            - :math:`P_s (1 + D_s I_s)`
            - :math:`P_s I_s`
            - :math:`P_s D_s`

    The derivative is computed by a `DERIV` block which implements a
    first-order system

    .. math::

        \frac{s}{s/a + 1}

    where the real pole :math:`a=` ``-D_filt`` can be positioned appropriately.

    If ``I_limit`` is provided it specifies the limits of the integrator output.  The
    integrator state is clipped to these limits, which can be used to prevent integrator
    windup.  The limits can be specified as:

    * a scalar :math:`a` the integrator state is clipped to the interval :math:`[-a, a]`
    * a 2-tuple :math:`(a,b)` the integrator state is clipped to the interval :math:`[a,
      b]`

    Examples::

        pid = bd.PID(P=3, D=2, I=1)

    ..note:: The result is a subsystem which will be expanded into 12 blocks for the
        PID case, fewer for the PI or PD cases.

    .. warning::
        This block has a direct feedthrough term (by definition), and depending on how it is used
        in a system it may introduce an an algebraic loop which will be flagged at
        ``compile`` time.

    .. versionchanged:: 1.2.0
        The pole is now at ``-D_pole`` instead of ``-1/D_pole``.

    :seealso: :class:`Deriv` :class:`Integrator`
    """

    nin = 2
    nout = 1

    def __init__(
        self,
        P: float = 0.0,
        D: float = 0.0,
        I: float = 0.0,
        D_pole: float = 1,
        I_limit: float | tuple[float, ...] | list[float] | None = None,
        structure: str = "parallel",
        **blockargs: Any,
    ) -> None:
        r"""
        :param type: the controller type, defaults to "PID"
        :type type: str, optional
        :param P: proportional gain, defaults to 0
        :type P: float
        :param D: derivative gain, defaults to 0
        :type D: float
        :param I: integral gain, defaults to 0
        :type I: float
        :param D_pole: filter pole for derivative estimate, defaults to 1 rad/s
        :type D_pole: float
        :param I_limit: integral limit
        :type I_limit: float or 2-tuple
        :param structure: the structure of the PID implementation, "parallel" (default), "series", "standard|ideal"
        :param blockargs: |BlockOptions|
        :type blockargs: dict
        """

        bd = blockargs["bd"]
        subsystem = bd.runtime.blockdiagram()

        Pblock = subsystem.GAIN(P, name="P")  # proportional gain block
        type = "P"

        if I != 0:
            # if the I term is required, create the block
            type += "I"
            integ_args = {}
            if isinstance(I_limit, float):
                integ_args["min"] = -I_limit
                integ_args["max"] = I_limit
            elif isinstance(I_limit, tuple) and len(I_limit) == 2:
                integ_args["min"] = I_limit[0]
                integ_args["max"] = I_limit[1]

            Iblock = subsystem.INTEGRATOR(
                gain=I, name="I", **integ_args
            )  # integral block with gain I

        if D != 0:
            type += "D"
            # if the D term is required, create the blocks
            Dblock = subsystem.DERIV(alpha=D_pole, gain=D, name="D")  # derivative block

        error_sum = subsystem.SUM("-+", name="ERR")  # error summing junction
        inp = subsystem.INPORT(2, name="INP")  # PID block inputs
        outp = subsystem.OUTPORT(1, name="OUTP")  # PID block output

        subsystem.connect(inp, error_sum)

        print("PID type:", type, "structure:", structure)
        # for each case sum the various terms
        if structure == "parallel":
            if type == "PID":
                out_sum = subsystem.SUM("+++", name="SUM")
                subsystem.connect(error_sum, Pblock, Dblock, Iblock)
                subsystem.connect(Pblock, out_sum[0])
                subsystem.connect(Iblock, out_sum[1])
                subsystem.connect(Dblock, out_sum[2])
            elif type == "PI":
                out_sum = subsystem.SUM("++", name="SUM")
                subsystem.connect(error_sum, Pblock, Iblock)
                subsystem.connect(Pblock, out_sum[0])
                subsystem.connect(Iblock, out_sum[1])
            elif type == "PD":
                out_sum = subsystem.SUM("++", name="SUM")
                subsystem.connect(error_sum, Pblock, Dblock)
                subsystem.connect(Pblock, out_sum[0])
                subsystem.connect(Dblock, out_sum[1])

            subsystem.connect(out_sum, outp)

        elif structure == "series":
            # cascade of P, I and D blocks with summing junctions between them

            subsystem.connect(error_sum, Pblock)

            if "I" in type:
                sum1 = subsystem.SUM("++", name="SUM_I")

                subsystem.connect(Pblock, Iblock, sum1[1])
                subsystem.connect(Iblock, sum1[0])
                I_out = sum1
            else:
                I_out = Pblock

            if "D" in type:
                sum2 = subsystem.SUM("++", name="SUM_D")
                subsystem.connect(I_out, Dblock, sum2[1])
                subsystem.connect(Dblock, sum2[0])
                D_out = sum2
            else:
                D_out = I_out

            subsystem.connect(D_out, outp)

        elif structure in ("standard", "ideal"):
            # P in series with parallel D and I
            if type == "PID":
                out_sum = subsystem.SUM("+++", name="SUM")
                subsystem.connect(error_sum, Pblock)
                subsystem.connect(Pblock, out_sum[0], Iblock, Dblock)
                subsystem.connect(Iblock, out_sum[1])
                subsystem.connect(Dblock, out_sum[2])
            elif type == "PI":
                out_sum = subsystem.SUM("++", name="SUM")
                subsystem.connect(error_sum, Pblock)
                subsystem.connect(Pblock, out_sum[0], Iblock)
                subsystem.connect(Iblock, out_sum[1])
            elif type == "PD":
                out_sum = subsystem.SUM("++", name="SUM")
                subsystem.connect(error_sum, Pblock)
                subsystem.connect(Pblock, out_sum[0], Dblock)
                subsystem.connect(Dblock, out_sum[1])

            subsystem.connect(out_sum, outp)

        super().__init__(subsystem=subsystem, **blockargs)


if __name__ == "__main__":  # pragma: no cover
    from pathlib import Path
    import subprocess
    import sys

    root = Path(__file__).resolve().parents[3]
    test_file = (
        root / "tests" / "blocks" / f"test_blocks_{Path(__file__).stem.lower()}.py"
    )

    if not test_file.exists():
        print(f"No module unit tests found for {Path(__file__).name}: {test_file}")
        raise SystemExit(0)

    raise SystemExit(subprocess.call([sys.executable, "-m", "pytest", str(test_file)]))
